### ISSUE TITLE
Axpert has Add-on fails to install

### ISSUE THREAD

**Issue by zeane** [MindFreeze/home-assistant-addons#1]
When trying to install either add-ons -  I'm seeing a FAILED TO INSTALL ADD-ON errors:

----------
Axpert Command - Error message:

The command '/bin/ash -o pipefail -c apk add --no-cache python2 git && python2 -m ensurepip && rm -r /usr/lib/python*/ensurepip && git clone https://github.com/aquarat/mpp-solar.git . && pip install --upgrade paho-mqtt && python ./setup.py install' returned a non-zero code: 1

-------------
Axpert Inverter - Error message:

The command '/bin/ash -o pipefail -c apk add --no-cache python2 && python2 -m ensurepip && rm -r /usr/lib/python*/ensurepip && pip install --upgrade pip setuptools crcmod paho-mqtt && rm -r /root/.cache' returned a non-zero code: 1

PLEASE ADV8SE FURTHER or let me know if you require any further information

Thanks - Anthony

**Comment by MindFreeze** [comment]
Looks like this is completely broken now and I have to rewrite it with python3. Unfortunately I don't have any time for this atm and don't know when I will.

**Comment by zeane** [comment]
Thanks for the response back. I look forward to when you do have sone time to work on this. There really is not much out there - so I find your efforts (along with many other's out there) most gracious ! There really is a great need for this facility!

Take care...

ANTHONY in Cape Town

**Comment by MindFreeze** [comment]
Checkout [this comment](https://github.com/MindFreeze/hassio-axpert/commit/0aab6e68bba688aa72267dba5025534ade5aad99#commitcomment-76609756) for some alternatives
